### ISSUE TITLE
dirty checking을 이용한 update query 변경이 있는 컬럼만 query 날아가게 변경

### ISSUE THREAD

**Issue by qoxogus** [Team-Ampersand/Dotori-server#259]
현재 dirty checking을 하여 update query가 날아가게되면 모든 컬럼이 update쿼리가 날아가게 됩니다.
변경점이 있는 컬럼에만 query가 날아갈 수 있도록 변경해야합니다. 
(전체 필드로 update쿼리가 나가게되면 컬럼이 많을수록 데이터베이스가 부담되기 때문)

위 내용에 대해 자세히 알고싶으면 
`@DynamicUpdate`에 대해 구글링 해보시길 바랍니다.

**Comment by TeMlN** [comment]
@DynamicUpdate가 동작하는 과정중에 성능저하의 원인이 발생할 수도 있고 성능은 쿼리가 날라가는 갯수에 따라 지장이 있고 한 쿼리에 몇개의 필드가 추가된다고 해서 성능저하 크게 된다고 하지않는 조사결과에 따라 해당 issue는 close 하겠습니다~
