### ISSUE TITLE
자습 신청 비즈니스 로직이 multi-thread 환경에서 thread-safe 하지 못한 것 같습니다.

### ISSUE THREAD

**Issue by jyeonjyan** [Team-Ampersand/Dotori-server#342]
## 문제상황
<img width="493" alt="CleanShot 2022-04-21 at 13 38 51@2x" src="https://user-images.githubusercontent.com/67095821/164380187-721629e7-5154-4daf-b623-471a794053ba.png">

## 예상 시나리오
`SelfStudyServiceImpl` 객체는 스프링 IoC 컨테이너에서 기본적으로 singleton bean으로 관리되는 것 같습니다. 
우선 [해당 Line 메소드](https://github.com/Team-Ampersand/Dotori-server/blob/ad3ffc463ebff507be795dfeb7a29d8429acda45/src/main/java/com/server/Dotori/domain/self_study/service/Impl/SelfStudyServiceImpl.java#L51)에서 언제 어느 방식으로 자습신청인원이 조회되는지 모르겠지만 (`repo.count()`를 추적할 수 없음.)

해당 문제상황은 자습신청 같은 같은 시간 (구간)내에 비교적 많은 트래픽이 몰려 `multi-thread` 환경에서 해당 비즈니스 로직이 `thread-safe`하지 못했기 때문에 발생한 것 같습니다.

ex) `A 사용자`와 `B 사용자`가 동시에 자습신청인원을 조회해서 신청된 인원 `20명`이라는 값을 얻었을 때를 가정합니다.
둘 다 자습신청 상태를 update 를 하고자 한다면 결과적으로 A와 B모두 `20+1=21` 21번째 자습신청자가 되게 됩니다. (데이터 정합성의 문제가 발생함)

## 제안합니다

자습신청인원을 집계하는 대상 객체가 무엇인지 확인이 어려워 DB 락이나 동기화 처럼 명확한 답을 드리기 어렵습니다.

기숙사 그리고 자습신청이라는 도메인이 동시성 이슈로 인해 비용이 많이 들 것이라고(crictical) 예상하지는 않지만.
더 매끄러운 서비스를 위해 팀 내 의사결정을 제안드립니다.

자세한 비즈니스 요구사항과 현재 workflow를 알려주신다면 자세한 솔루션을 찾는 과정을 도와드릴 수 있을 것 같습니다.
감사합니다 🙇🏻‍♂️

**Comment by qoxogus** [comment]
먼저 저희 자습신청 feature에 대해 관심을 가져주셔서 감사합니다.

현재 저희는 자습신청 요청이 들어올 때 마다 자습신청 인원을 count 하고 있으며,
count가 50 미만일 때만 자습신청이 완료되는 방식입니다.
정말 동시에 요청이 들어와 50명이 넘었는데도 자습신청이 되었다 라는 상황을 가정한다면
**49** 라는 결과 값의 `count query`가 **동시에 조회** 되었을 것으로 예상되고있습니다.

저희도 해결 방법에 대해 논의 중에 있으며, 
정확한 workflow를 알고싶으시다면 개인적으로 연락 부탁드립니다.

다시 한번 저희 서비스에 관심을 가져주셔서 감사합니다 🙇‍♂️
