### ISSUE TITLE
동명이인 회원가입

### ISSUE THREAD

**Issue by qoxogus** [Team-Ampersand/Dotori-server#81]
### 현재 동명이인이 저희 서비스를 사용하려고 하면 회원가입을 할 수 없습니다.
> 동명이인 중 최초 가입자만 회원가입이 가능합니다.

저희는 학교 서비스이기 때문에 동명이인이 있을 수 있으며 Entity를 설계할 때도 동명이인을 고려하여
**username에는 unique제약조건을 걸지 않았습니다.**

하지만 제가 현재 테스트하며 **동명이인으로 회원가입할 수 없다는 것을 발견**하였고 이유는
**회원가입 서비스 로직 설계 문제**입니다.

회원가입할 때에 **같은 이름으로 가입되어있는 회원이 있는지 확인하는 로직이 있는것을 확인**하였습니다.
@KyungJunNoh 저희 회원가입 로직 갈아엎을 예정이였으니
함께 수정해주시길 바랍니다. 😊

<img width="800" alt="스크린샷 2021-09-06 오후 12 17 02" src="https://user-images.githubusercontent.com/69895394/132155756-a070fa3c-9453-4a3d-8596-323d2ef6f102.png">

**Comment by KyungJunNoh** [comment]
확인했습니다 코드 수정할때 참고하도록 하겠습니다
