### ISSUE TITLE
동명이인이 회원가입 후 조회할 때

### ISSUE THREAD

**Issue by qoxogus** [Team-Ampersand/Dotori-server#96]
### 동명이인이 회원가입 후 상벌점, 학생정보변경 페이지 조회할 때
이와와같은 `Exception`이 발생합니다. (자습신청 전체, 학년반 조회에서도 마찬가지)
![image](https://user-images.githubusercontent.com/69895394/132787414-a6956c49-3054-4fb4-abf6-7d25d9fa2b80.png)

위 사진은 학생들의 **정보, 상벌점 목록을 조회**하는 로직에서 발생한 `Exception`입니다. (자습신청 전체, 학년반 조회에서도 마찬가지)
동명이인으로 회원가입한 사람의 학번 등이 달라도 
동명이인이 포함되어있지 않은 학년반을 조회해도 발생하는 `Exception`입니다...

조사해본 결과 **mapping 문제**인 것 같습니다.
제가 생각했을 때  `findByUsername`을 한다면 같은 이름이 있는 상태..  (무엇을 조회해야할까?)
이런경우 때문인 것 같습니다. (매핑 문제)

제가 생각한 방안은 username에도 unique 제약조건을 건 뒤
동명이인 중 회원가입을 늦게 하는사람이 이름뒤에 `.`을 붙이라던지 
이런식으로 알려주어 조취를 취해야할 것 같습니다. (이렇게 하면 해결될 문제인 것 같긴 합니다.)

**Comment by KyungJunNoh** [comment]
말씀하신대로 username 에 unique 제약조건을 걸어서 처리하였습니다.
v1 때에는 unique속성을 걸어둘거지만 v2때는 다른 로직을 생각하여 동명이인도 순조롭게 회원가입할수 있게 생각해보도록 하겠습니다.

**Comment by qoxogus** [comment]
jwt의 `payload`와 `subject`를 `email`로 설정하고 
`loadByUsername`을 `email`로 load하게 만든다면 (email은 무조건 unique)
동명이인 회원가입을 도입할 수 있을 것 같습니다.
(v2고려)
